name: Deploy to GCP VM

on:
  push:
    branches: [ "dev" ] # dev 브랜치에 코드가 push될 때만 알아서 실행됨

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: VM에 접속해서 최신 코드 받고 도커 재실행하기
      uses: appleboy/ssh-action@master
      with:
        host: 104.197.144.27
        username: github-actions
        key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        script: |
          set -e
          sudo chown -R ye0nwu1118:ye0nwu1118 /home/ye0nwu1118/memit
          sudo -u ye0nwu1118 git -C /home/ye0nwu1118/memit fetch origin
          sudo -u ye0nwu1118 git -C /home/ye0nwu1118/memit reset --hard origin/dev
          sudo sh -c '
            cd /home/ye0nwu1118/memit
            docker compose up -d --build
            docker compose restart nginx
          '
